docker_img="frr_ditg:v1"
updatemap=/usr/local/bin/updatemap
setprop=/usr/local/bin/setprop.o
tracer=/usr/local/bin/tracer
numgs=2
gs_coords="50.110924,8.682127;46.635700,14.311817"
numterm=2
termc="term1-gs1;term2-gs2"
maxp=12
maxs=8
delay_west=1
delay_east=1
delay_north=1
delay_south=1
delay_gssat=1
ip="yes"
ospf="yes"
hello_interval="10"
mapsize=2048
altitude=550
inclination=70
duration=3600
antenna_inclination_angle=25
